### ISSUE TITLE
Cannot connect to Tapo P110

### ISSUE THREAD

**Issue by Alfredsche** [fishbigger/TapoP100#134]
After firmware update it is not possible to connect to Tapo P110
`pip install git+https://github.com/almottier/TapoP100.git@main` updated, but login problem still persits. 
Firmware 1.3.0 Build 230905 Rel. 152200

**Comment by realhuno** [comment]
Yes, i can confirm. Not working anymore.... with node-red and the Tapo Api.....  Unexpected Error Code: 1003

**Comment by baishi** [comment]
Exactly the same problem here, was working like a charm until Firmware 1.3.0 Build 230905 Rel.152200

**Comment by sjparle** [comment]
think I'm having the same issue, my program now fails on plug.handshake(), was working fine last week

    plug.handshake() #Creates the cookies required for further methods
    ^^^^^^^^^^^^^^^^
  File "C:\Users\sean\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyP100\PyP100.py", line 129, in handshake
    encryptedKey = r.json()["result"]["key"]
                   ~~~~~~~~^^^^^^^^^^
KeyError: 'result'

**Comment by Addams666** [comment]
+1

**Comment by V01ee** [comment]
+1 same problem here:

  File "/usr/local/lib/python3.11/dist-packages/PyP100/PyP100.py", line 129, in handshake
    encryptedKey = r.json()["result"]["key"]
                   ~~~~~~~~^^^^^^^^^^
KeyError: 'result'

**Comment by weaster007** [comment]
Same here, do you guys think this can be fixed?

**Comment by R4ykoo** [comment]
+1 same problem with the firmware update

**Comment by Blafy** [comment]
> Same here, do you guys think this can be fixed?

Using the fix of @almottier, the issue is solved, see #128

**Comment by weaster007** [comment]
> > Same here, do you guys think this can be fixed?
> 
> Using the fix of @almottier, the issue is solved, see #128

Thanks a lot with this:
`pip install --force-reinstall git+https://github.com/almottier/TapoP100.git@main`
It worked perfectly again.

**Comment by Alfredsche** [comment]
For me it is still not working after installing.
Installating ended successful (pip install --force-reinstall git+https://github.com/almottier/TapoP100.git@main) but problem persists.
I tried with Linux (Raspbian) and Windows 10.
Failure message of Python script:
`Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "C:\Users\AS\AppData\Roaming\Python\Python311\site-packages\PyP100\PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "C:\Users\AS\AppData\Roaming\Python\Python311\site-packages\PyP100\auth_protocol.py", line 110, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
Error: {'error_code': 1003}
Failed to initialize protocol OldProtocol
Traceback (most recent call last):
  File "C:\Users\AS\AppData\Roaming\Python\Python311\site-packages\PyP100\PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "C:\Users\AS\AppData\Roaming\Python\Python311\site-packages\PyP100\auth_protocol.py", line 244, in Initialize
    result = self._request_raw("handshake", {"key": public_key})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AS\AppData\Roaming\Python\Python311\site-packages\PyP100\auth_protocol.py", line 173, in _request_raw
    raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: 1003`

**Comment by WouterGritter** [comment]
> > > Same here, do you guys think this can be fixed?
> > 
> > 
> > Using the fix of @almottier, the issue is solved, see #128
> 
> Thanks a lot with this: `pip install --force-reinstall git+https://github.com/almottier/TapoP100.git@main` It worked perfectly again.

Can confirm this works! Thanks a lot!

**Comment by langstroth2** [comment]
Can confirm the fix works, thank you. I had to download and install the two updated code files manually on to the Pi - couldn't get pip to do the install.

**Comment by realzoulou** [comment]
Confirm also that https://github.com/almottier/TapoP100 (0.1.4) works

**Comment by Alfredsche** [comment]
Yes, now it is working for me, also. Thank you

**Comment by V01ee** [comment]
> > Same here, do you guys think this can be fixed?
> 
> Using the fix of @almottier, the issue is solved, see #128

Ty I confirm this works with the Firmware 1.3.0 Build 230905 Rel. 152200
