### ISSUE TITLE
Error code 1501: Passwords must not exceed 8 characters

### ISSUE THREAD

**Issue by audoh** [fishbigger/TapoP100#4]
If your password is longer than 8 characters, you will always get a 1501.

However, your password **can** contain non-alphanumeric characters.

**Comment by audoh** [comment]
Okay, this seems like it might actually be a length limit. Currently trying to narrow down the exact limit, but I can use symbols if the password is 8 characters.

**Comment by SvenLudwig202** [comment]
Just wanted to share my own experience regarding this issue.
I've just implemented a simple script for some home automation and my password is well beyond 8 characters.
I haven't run into any issues though. Maybe the update for my P100 plugs I installed yesterday fixed this on their end?
Went from 1.3.3 to 1.3.4.

**Comment by audoh** [comment]
My devices are on 1.3.4 as well, and I haven't updated them since before I tested this. How strange, there must be something else to it than just length or special characters.

**Comment by DanieleLupo94** [comment]
Hi. Any solution?
I have changed my password to **1234567o** but still not working...

**Comment by jondurrant** [comment]
Also get the 1501 error. Though notice that https://github.com/K4CZP3R/tapo-p100-python experiment does not have the same issue. Works fine even with my long password.

**Comment by fishbigger** [comment]
I am still working on a fix for this but thanks for all your help!

**Comment by VinterMute** [comment]
I get some problem and change password only 8 ch and this work

**Comment by fishbigger** [comment]
I believe I finally fixed this in the latest version (0.1.0) :)
